spring.application.name=taskmanagersecurity

spring.datasource.url=jdbc:mysql://localhost:3306/taskmanager?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Scar2511@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,env,beans,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always


# Info Endpoint
info.app.name=Task Manager API
info.app.description=A comprehensive task management system
info.app.version=1.0.0


# Metrics
management.metrics.tags.application=${spring.application.name}
server.port=8080

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc57452c0620004a39893410e8220770d045d944
security.jwt.expiration-time=5000000
