spring.application.name=boot-jpa

spring.datasource.url=jdbc:mysql://localhost:3306/springjpa1
spring.datasource.username=root
spring.datasource.password=Scar2511@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100