spring.application.name=HibernateOnce
spring.datasource.url=jdbc:mysql://localhost:3306/nativeOnce
spring.datasource.username=root
spring.datasource.password=Scar2511@#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

