spring.application.name=bootapi-twice

spring.datasource.url=jdbc:mysql://localhost:3306/bootapitwice
spring.datasource.username=root
spring.datasource.password=Scar2511@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
