spring.application.name=CrudOperations

spring.datasource.url=jdbc:mysql://localhost:3306/crudnate
spring.datasource.username=root
spring.datasource.password=Scar2511@#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#  spring.application.name :
#  Sets the unique identifier for your Spring Boot project.

#  spring.datasource.url :
#  Specifies the database location and schema name (crudnate).

#  spring.datasource.username/password :
#  Credentials used to authenticate with your MySQL server.

#  spring.jpa.hibernate.ddl-auto :
#  Automatically updates your database schema based on your Java entities.

#  spring.jpa.show-sql :
#  Prints the generated SQL queries to the console for debugging.

#  spring.jpa.properties.hibernate.dialect :
#  Helps Hibernate generate SQL syntax specific to the MySQL version you are using.

